<a href="https://colab.research.google.com/github/Bilol2747/python_darslarim/blob/main/Array(massive).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
data1=[3, 5, 8, 9 ]
arr1=np.array(data1)

In [4]:
data1

[3, 5, 8, 9]

In [5]:
arr1

array([3, 5, 8, 9])

In [6]:
data2=(4, 5, 8, 9)
arr2=np.array(data2)

In [7]:
data2

(4, 5, 8, 9)

In [8]:
arr1

array([3, 5, 8, 9])

#Massiv o'lchami

In [10]:
arr1.ndim

1

In [11]:
arr2.ndim

1

In [12]:
data3=[[1, 2, 3, 4], [5, 6, 7, 8]]
arr3=np.array(data3)

In [14]:
arr3.ndim

2

# New Section

In [19]:
arr3.shape

(1, 4)

In [21]:
arr3.size

4

In [22]:
arr3

array([[1, 2, 3, 4]])

In [23]:
arr4=np.zeros(shape=(2, 4))
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
arr5=np.ones((2, 4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
arr6=np.arange(4, 20, 2)
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
arr7=np.arange(20)
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])