<a href="https://colab.research.google.com/github/Bilol2747/python_darslarim/blob/main/Boolen(massive).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


# New Section

In [ ]:
names=np.array(['Hasan', 'Husan', 'Javvohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Javvohir', 'Elyor'], dtype='<U8')

In [ ]:
data=np.random.randn(4, 3)
data

array([[-0.78897495,  0.66608225,  0.5041088 ],
       [-0.15911672, -0.72259174, -0.18232609],
       [ 0.81335711, -1.80596814, -0.36906068],
       [ 1.03549569, -0.74819716, -0.66864961]])

In [ ]:
names=='Hasan'

array([ True, False, False, False])

In [ ]:
data[names=='Hasan']

array([[-0.78897495,  0.66608225,  0.5041088 ]])

In [ ]:
data[names=='Elyor']

array([[ 1.03549569, -0.74819716, -0.66864961]])

In [ ]:
data[names=='Hasan',1:]

array([[0.66608225, 0.5041088 ]])

In [ ]:
data[names=='Javvohir', :]

array([[ 0.81335711, -1.80596814, -0.36906068]])

In [ ]:
data[names!='Hasan']

array([[-0.15911672, -0.72259174, -0.18232609],
       [ 0.81335711, -1.80596814, -0.36906068],
       [ 1.03549569, -0.74819716, -0.66864961]])

In [ ]:
print(names)
print(data)

['Hasan' 'Husan' 'Javvohir' 'Elyor']
[[-0.78897495  0.66608225  0.5041088 ]
 [-0.15911672 -0.72259174 -0.18232609]
 [ 0.81335711 -1.80596814 -0.36906068]
 [ 1.03549569 -0.74819716 -0.66864961]]


In [ ]:
mask=(names=='Hasan')| (names=='Javvohir')
mask

array([ True, False,  True, False])

In [ ]:
data[mask]

array([[-0.78897495,  0.66608225,  0.5041088 ],
       [ 0.81335711, -1.80596814, -0.36906068]])

In [ ]:
data

array([[-0.78897495,  0.66608225,  0.5041088 ],
       [-0.15911672, -0.72259174, -0.18232609],
       [ 0.81335711, -1.80596814, -0.36906068],
       [ 1.03549569, -0.74819716, -0.66864961]])

In [ ]:
data[data<0]=0
data

array([[0.        , 0.66608225, 0.5041088 ],
       [0.        , 0.        , 0.        ],
       [0.81335711, 0.        , 0.        ],
       [1.03549569, 0.        , 0.        ]])

In [ ]:
sonlar=np.arange(0,9,1)
sonlar

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr1=np.arange(sonlar(3:)])
arr1

<ipython-input-35-9bacaf7d1d48>:1: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  arr1=np.arange(sonlar[3:3])


TypeError: only length-1 arrays can be converted to Python scalars

In [ ]:
sonlar1=[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]
sonlar1


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
arr1=np.array(sonlar1)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1[1,1]

5

In [ ]:
arr1.ndim

2

In [ ]:
dtype(arr1)

NameError: name 'dtype' is not defined

In [ ]:
sonlar2=np.array([[[0, 1, 2],
                   [3, 4, 5],
                   [6, 7, 8]],

                   [[9, 10, 11],
                    [12, 13, 14],
                    [15, 16, 17]],

                  [[18, 19, 20],
                   [21, 22, 23],
                   [24, 25, 26]]])
sonlar2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
sonlar2.ndim

3

In [ ]:
sl_sonlar2=sonlar2[0]
sl_sonlar2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
sl_sonlar2[1,2]

5

In [ ]:
sonlar2[2,2,2]

26

In [ ]:
names1=np.array(['bilol', 'saloh', 'sayfi', 'hasan'])
names1

array(['bilol', 'saloh', 'sayfi', 'hasan'], dtype='<U5')

In [ ]:
data2=np.random.randn(4,3)
data2

array([[ 0.51021066,  1.30518389, -0.84727851],
       [ 1.63009305,  1.26132577, -0.19085676],
       [-0.13614341,  0.03844438, -0.71202523],
       [-2.38243814,  0.96953414, -0.28386161]])

In [ ]:
names1=='bilol'

array([ True, False, False])

In [ ]:
data2[names1=='bilol']

array([[-0.98167875,  0.02857447, -0.65952558]])

# New Section

In [80]:
import numpy as np

In [81]:
A=np.arange(6).reshape(3,2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [82]:
A.T

array([[0, 2, 4],
       [1, 3, 5]])

In [83]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [84]:
A.swapaxes(1, 0)

array([[0, 2, 4],
       [1, 3, 5]])

In [85]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [86]:
np.dot(A, A.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])