<a href="https://colab.research.google.com/github/Bilol2747/python_darslarim/blob/main/mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [2]:
arr=np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

1.   List item
2.   List item



In [6]:
np.zeros(arr)

array([[[[[[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]]],


         [[[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0.

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [7]:
np.size(arr)

6

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [8]:
np.info(arr)

class:  ndarray
shape:  (6,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x36dc2b0
byteorder:  little
byteswap:  False
type: int64


#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [23]:
data=np.array(12)
vek=np.zeros(data)
vek


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
vek[5]=1
vek

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [28]:
vek1=np.arange(20,60)
vek1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [30]:
vek1[-1]

59

In [38]:
te_vek=-np.sort(-vek1)
te_vek

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


In [46]:
arr2=np.arange(12, 21) .reshape(3,3)
arr2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

`💡Ishora` reshape

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [51]:
data2=np.array([3, 7, 0, 0, 9, 0])
np.nonzero(data2)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [59]:
data3=np.random.randn(2, 2, 2)
data3

array([[[ 1.12682894,  0.21479298],
        [ 1.56327201,  0.64705498]],

       [[-0.01701604,  1.11791795],
        [ 0.12939211, -0.34939793]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [61]:
data4=np.random.randn(9, 9)
data4

array([[-1.86261206, -0.16009949,  0.32707283,  1.21168785,  0.05475635,
        -0.85667396,  0.01012651,  0.34163931,  1.16447904],
       [ 0.72156592, -1.02990065,  1.41228101,  1.21374918,  0.84097902,
        -2.18819374, -0.79932362,  0.32629775, -0.26542092],
       [-0.35421385,  0.08894974, -1.2418012 ,  1.46319391, -1.49032452,
         1.44099975,  1.64843196, -0.25995955, -1.27661112],
       [ 0.73168424, -1.09566303, -1.26619005, -0.64826225,  1.90280646,
         0.52781875,  0.25106894, -0.13924255,  1.08255687],
       [-3.19852582, -0.30895541, -1.06302877, -0.54608255, -1.82259625,
         1.23582006,  0.50544533,  0.28282065, -0.29544945],
       [-1.36940071,  1.05036178, -0.57067204,  0.72696625,  1.22586745,
        -3.01783325,  0.76273836,  0.49084087, -3.57570069],
       [-0.51777221, -1.30733444,  0.60413666, -0.36514092,  0.86685866,
        -0.8991493 ,  0.11595186,  0.67840187,  0.60452921],
       [ 0.88901128, -0.96191063,  0.52213579,  0.22864452, -0

In [62]:
np.min(data4)

-3.575700685180391

In [63]:
np.max(data4)

1.923126377218435

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [64]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1


False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [123]:

mat=np.random.randn(6, 3)
mat

array([[-0.27185214,  0.25877089, -0.42045285],
       [ 0.59177002, -0.12674602, -0.32337818],
       [-1.90422432, -0.36907943,  2.1067828 ],
       [ 0.45918754, -0.26123872,  0.57091636],
       [-0.50384359,  0.94824632,  0.0243237 ],
       [-0.25339803,  0.13068886, -1.11103494]])

In [124]:
mat1=np.random.randn(3, 4)
mat1


array([[-0.66543953,  0.90517342,  0.23566264, -0.51142886],
       [ 0.18035173,  0.06585773, -0.61496772, -1.78321165],
       [ 2.05360772, -1.31956505,  0.85184273,  0.60619185]])

In [125]:
mat.dot(mat1)

array([[-0.63587427,  0.32578362, -0.58136084, -0.57728533],
       [-1.08073794,  0.95402582, -0.05806455, -0.2726625 ],
       [ 5.52708744, -4.52799693,  1.57286503,  2.90913659],
       [ 0.81976185, -0.35492151,  0.75519768,  0.57708701],
       [ 0.55624664, -0.42571318, -0.68115802, -1.4184989 ],
       [-2.08943889,  1.24532059, -1.08651292, -0.77695116]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [106]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [110]:
a=np.array([1, 2])
b=np.array([4, 5])

In [113]:
a > b
cond= np.array([False, False])
result=np.where(cond, a, b)
result

array([4, 5])

In [122]:
a >= b
cond1= np.array([False, False])
result1=np.where(cond1, a, b)
result1

array([4, 5])

In [121]:
a < b
cond2=np.array([True, True])
result2=np.where(cond2, a, b)
result2

array([1, 2])

In [119]:
a <= b
cond3=np.array([True, True])
result3=np.where(cond3, a, b)
result3

array([1, 2])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [126]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-126-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-126-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-126-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [134]:
arr6=np.arange(3,8)
arr6


array([3, 4, 5, 6, 7])

In [135]:
arr7=np.arange(6, 12)
arr7

array([ 6,  7,  8,  9, 10, 11])

In [136]:
np.intersect1d(arr6, arr7)

array([6, 7])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [158]:
arr8=np.random.randn(3,3)
arr8

array([[ 0.95555149, -0.59092501,  0.02463124],
       [-1.42943433,  1.04960976, -0.2699793 ],
       [-1.17703028, -0.11088872,  1.30434798]])

In [159]:
np.floor(arr8)

array([[ 0., -1.,  0.],
       [-2.,  1., -1.],
       [-2., -1.,  1.]])

In [160]:
arr8.astype

<function ndarray.astype>

In [161]:
np.trunc(arr8)

array([[ 0., -0.,  0.],
       [-1.,  1., -0.],
       [-1., -0.,  1.]])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.





```
# This is formatted as code
```

`💡Ishora` np.arange

In [170]:
data4=np.random.randn(3, 3)
data4

array([[ 1.04500846, -1.69668877,  0.38574313],
       [ 1.04772616, -0.81099461, -1.76586383],
       [ 1.05914689, -0.47212357,  0.12513297]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [175]:
vek2=np.array([10, 2, 5, 7, 1, 6, 5, ])
vek2

array([10,  2,  5,  7,  1,  6,  5])

In [176]:
np.sort(vek2)

array([ 1,  2,  5,  5,  6,  7, 10])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [180]:
xarr=random.randn(2, 2)
xarr

array([[ 1.05199062,  0.67291917],
       [ 0.52909477, -1.53074013]])

In [182]:
yarr=random.randn(2, 2)
yarr

array([[-0.20579295, -0.16760948],
       [-0.88107797,  0.53879115]])

In [183]:
np.allclose(xarr, yarr)

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [184]:
print(mat)

[[-0.27185214  0.25877089 -0.42045285]
 [ 0.59177002 -0.12674602 -0.32337818]
 [-1.90422432 -0.36907943  2.1067828 ]
 [ 0.45918754 -0.26123872  0.57091636]
 [-0.50384359  0.94824632  0.0243237 ]
 [-0.25339803  0.13068886 -1.11103494]]


In [185]:
print(mat1)

[[-0.66543953  0.90517342  0.23566264 -0.51142886]
 [ 0.18035173  0.06585773 -0.61496772 -1.78321165]
 [ 2.05360772 -1.31956505  0.85184273  0.60619185]]


In [186]:
np.dot(mat, mat1)

array([[-0.63587427,  0.32578362, -0.58136084, -0.57728533],
       [-1.08073794,  0.95402582, -0.05806455, -0.2726625 ],
       [ 5.52708744, -4.52799693,  1.57286503,  2.90913659],
       [ 0.81976185, -0.35492151,  0.75519768,  0.57708701],
       [ 0.55624664, -0.42571318, -0.68115802, -1.4184989 ],
       [-2.08943889,  1.24532059, -1.08651292, -0.77695116]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [187]:
data9=random.randn(1,5)
data9

array([[0.26964643, 0.68401965, 0.30798992, 0.01304997, 0.14022912]])

In [203]:
max=argmax(data9)
max


1

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [205]:
np.datetime64(()

NameError: name 'now' is not defined

#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

#19- savol bilan bir xil

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [206]:
arr10=np.array([1, 2, 5, 4])

In [207]:
np.sum(arr10)

12

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [208]:
a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]

In [211]:
stride_tricks.as_strided(a, b)

NameError: name 'stride_tricks' is not defined

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [212]:
arr12=np.array([1, 4, 2, 5])


In [215]:
arr13=np.array([1, 2, 8, 9])

In [216]:
np.bincount(arr12, arr13)

array([0., 1., 8., 0., 2., 9.])

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`