<a href="https://colab.research.google.com/github/Bilol2747/Data_Analytics_Portfolio/blob/main/Python_skills.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
data=np.load("/content/sales_data (3).npy")

1. Massivdagi jami satrlar va ustunlar sonini aniqlang.


In [ ]:
print(f"Jami ustunlar soni: {data.shape[1]}")
print(f"Jami qatorlar soni: {data.shape[0]}")

Jami ustunlar soni: 5
Jami qatorlar soni: 100


2. Birinchi 10 ta yozuvni ekranga chiqaring.


In [ ]:
print(data[:10 ,:])

[[      7       4      48   40746 1955808]
 [      4       2      16   42352  677632]
 [      8       1      33   49790 1643070]
 [      5       5       9   15600  140400]
 [      7       3       6   39124  234744]
 [     10       4      16   37643  602288]
 [      3       3      29   19007  551203]
 [      7       3       3   47410  142230]
 [      8       1      20   18208  364160]
 [      5       3      36   28589 1029204]]


3.Faqat Product_ID ustunini ajratib oling.


In [ ]:
print(data[:, :1])

[[ 7]
 [ 4]
 [ 8]
 [ 5]
 [ 7]
 [10]
 [ 3]
 [ 7]
 [ 8]
 [ 5]
 [ 4]
 [ 8]
 [ 8]
 [ 3]
 [ 6]
 [ 5]
 [ 2]
 [ 8]
 [ 6]
 [ 2]
 [ 5]
 [ 1]
 [10]
 [ 6]
 [ 9]
 [ 1]
 [10]
 [ 3]
 [ 7]
 [ 4]
 [ 9]
 [ 3]
 [ 5]
 [ 3]
 [ 7]
 [ 5]
 [ 9]
 [ 7]
 [ 2]
 [ 4]
 [ 9]
 [ 2]
 [10]
 [ 9]
 [10]
 [ 5]
 [ 2]
 [ 4]
 [ 7]
 [ 8]
 [ 3]
 [ 1]
 [ 4]
 [ 2]
 [ 8]
 [ 4]
 [ 2]
 [ 6]
 [ 6]
 [10]
 [ 4]
 [ 6]
 [ 2]
 [10]
 [ 2]
 [10]
 [ 4]
 [ 8]
 [ 7]
 [ 9]
 [ 8]
 [ 5]
 [ 2]
 [ 5]
 [ 8]
 [10]
 [ 9]
 [ 9]
 [ 1]
 [ 9]
 [ 7]
 [ 9]
 [ 8]
 [ 1]
 [ 8]
 [ 8]
 [ 3]
 [ 1]
 [ 8]
 [ 3]
 [ 3]
 [ 1]
 [ 5]
 [10]
 [ 7]
 [10]
 [ 9]
 [ 7]
 [ 9]
 [ 8]]


4. Faqat Revenue ustunini ajratib oling.

In [ ]:
print(data[:, 4:])

[[1955808]
 [ 677632]
 [1643070]
 [ 140400]
 [ 234744]
 [ 602288]
 [ 551203]
 [ 142230]
 [ 364160]
 [1029204]
 [ 521607]
 [1201512]
 [ 127905]
 [ 832732]
 [ 574220]
 [ 429440]
 [ 288512]
 [ 422341]
 [ 353067]
 [ 407600]
 [ 799188]
 [ 823374]
 [ 644080]
 [  29778]
 [ 403051]
 [1248352]
 [1068625]
 [1654650]
 [ 243087]
 [1494510]
 [1339890]
 [1958502]
 [ 610925]
 [  98098]
 [ 337488]
 [ 729820]
 [2197296]
 [1300362]
 [  41458]
 [  44177]
 [ 517632]
 [ 453012]
 [ 112665]
 [1849038]
 [ 505632]
 [ 262710]
 [1998914]
 [1385720]
 [ 392293]
 [ 898368]
 [ 533680]
 [  96027]
 [ 687520]
 [ 354720]
 [ 408144]
 [ 528936]
 [ 183205]
 [ 710255]
 [ 167144]
 [1279692]
 [1230668]
 [ 936120]
 [ 841940]
 [ 809235]
 [1006368]
 [1090525]
 [1340920]
 [ 816925]
 [1197381]
 [ 738432]
 [ 679742]
 [ 715482]
 [  50676]
 [ 437185]
 [ 595776]
 [1008559]
 [1062288]
 [ 430683]
 [ 126424]
 [1046067]
 [ 152264]
 [ 883953]
 [ 678816]
 [ 504040]
 [ 397872]
 [ 119553]
 [  53961]
 [ 842639]
 [1285020]
 [2267184]
 [ 324228]

5. Units_Sold ustunidagi eng kichik va eng katta qiymatlarni toping.

In [ ]:
print(f"Eng katta qiymat: {data[:, 2:3].max()}")

Eng katta qiymat: 50


In [ ]:
print(f"Eng kichik qiymat: {data[:, 2:3].min()}")

Eng kichik qiymat: 1


6. Barcha sotuvlardan umumiy tushumni (Revenue yig‘indisi) hisoblang.

In [ ]:
print(f"Umumiy tushum: {data[:, 4].sum()}")

Umumiy tushum: 74984801


7. O‘rtacha Units_Sold qiymatini toping.

In [ ]:
print(data[:, 2].mean().round())  # mahsulot dona bo'lgani uchun round() ni ishlatdm

26.0


8. O‘rtacha Unit_Priceni hisoblang.

In [ ]:
print(data[:, 3].mean())

30065.54


9. Sotuvlarning median Revenue qiymatini toping.


In [ ]:
print(np.median(data[:,4]))

660856.0


10. Units_Sold ustunining standart og‘ishini (std) hisoblang.




In [ ]:
print(np.std(data[:,2]))

14.214837318801788


11. Har bir mahsulot (Product_ID) bo‘yicha umumiy tushumni hisoblang.


In [ ]:
id_numb=np.unique(data[:, 0])
for id in id_numb:
  summa=data[data[:, 0]==id, 4].sum()
  print(f"Mahsulot id : {id} -- Soni {summa}")



Mahsulot id : 1 -- Soni 4258550
Mahsulot id : 2 -- Soni 5626405
Mahsulot id : 3 -- Soni 8274238
Mahsulot id : 4 -- Soni 7911690
Mahsulot id : 5 -- Soni 5952030
Mahsulot id : 6 -- Soni 2770584
Mahsulot id : 7 -- Soni 8226282
Mahsulot id : 8 -- Soni 10609719
Mahsulot id : 9 -- Soni 11767614
Mahsulot id : 10 -- Soni 9587689


12. Har bir do‘kon (Store_ID) bo‘yicha sotilgan jami dona sonini hisoblang.


In [ ]:
store_id=np.unique(data[:, 1])
for id in store_id:
  numbers=data[data[:, 0]==id, 3].sum()
  print(f"Store id : {id} -- Soni {numbers}")


Store id : 1 -- Soni 256788
Store id : 2 -- Soni 278476
Store id : 3 -- Soni 282167
Store id : 4 -- Soni 328897
Store id : 5 -- Soni 241314


13. Eng ko‘p tushum qilgan mahsulot IDni toping.

In [ ]:
max_sum=data[:, 3].max()
id=data[data[:, 3]==max_sum, 0]
print(f"Eng kop tushum qilgan mahsulot id: {id}")

Eng kop tushum qilgan mahsulot id: [9]


14. Eng ko‘p tushum qilgan do‘kon IDni aniqlang.

In [ ]:
store_id=data[data[:, 3]==max_sum, 1]
print(f"Eng kop tushum qilgan mahsulot id: {store_id}")

Eng kop tushum qilgan mahsulot id: [4]


15. 1-raqamli mahsulot bo‘yicha jami tushumni hisoblang.

In [ ]:
sum=data[data[:, 0]==1, 4].sum()
print(f"1 id- jami summa--{sum}")

1 id- jami summa--4258550


16.  20 donadan ko‘p sotilgan yozuvlarni ajratib oling.

In [ ]:
data1=data[data[:, 2]>20, :]
print(data1.shape)   # shartni bajargan mahsulotlar soni

(59, 5)


17.  Narxi 40 000 so‘mdan yuqori bo‘lgan mahsulotlarni ajrating.




In [ ]:
data2=data[data[:, 3]>40000, :]
print(data2.shape)

(27, 5)


18. Faqatgina Store_ID = 3 bo‘lgan yozuvlarni chiqaring.

In [ ]:
data3=data[data[:, 1]==3, :]
print(data3)

[[      7       3       6   39124  234744]
 [      3       3      29   19007  551203]
 [      7       3       3   47410  142230]
 [      5       3      36   28589 1029204]
 [      8       3      26   46212 1201512]
 [      5       3      32   13420  429440]
 [      1       3      18   45743  823374]
 [      7       3      23   10569  243087]
 [      5       3      35   17455  610925]
 [      3       3       7   14014   98098]
 [      5       3       9   29190  262710]
 [      4       3      20   34376  687520]
 [      6       3      49   14495  710255]
 [      6       3       8   20893  167144]
 [      2       3      20   42097  841940]
 [     10       3      25   43621 1090525]
 [      8       3      16   37236  595776]
 [      9       3      33   31699 1046067]
 [      1       3      17   49567  842639]
 [     10       3      46   31136 1432256]
 [      7       3      30   18311  549330]
 [      8       3      27   35945  970515]]


19.  Tushumi 1 000 000 so‘mdan yuqori bo‘lgan yozuvlarni chiqaring.


In [ ]:
data4=data[data[:, 4]>1000000]
print(data4.shape)

(29, 5)


20.  Units_Sold 10 dan kichik bo‘lgan sotuvlarni chiqaring.

In [ ]:
data5=data[data[:, 2]<10]
print(data5)

[[     5      5      9  15600 140400]
 [     7      3      6  39124 234744]
 [     7      3      3  47410 142230]
 [     8      1      3  42635 127905]
 [     2      1      7  41216 288512]
 [     6      4      1  29778  29778]
 [     3      3      7  14014  98098]
 [     2      1      2  20729  41458]
 [     4      5      1  44177  44177]
 [    10      4      5  22533 112665]
 [     5      3      9  29190 262710]
 [     1      1      3  32009  96027]
 [     6      3      8  20893 167144]
 [     2      4      2  25338  50676]
 [     1      1      4  31606 126424]
 [     8      5      8  49734 397872]
 [     8      1      7  17079 119553]
 [     3      1      3  17987  53961]
 [     9      2      8  47945 383560]]


21.  Har bir mahsulot uchun o‘rtacha tushumni hisoblang.

In [ ]:
id_numb=np.unique(data[:, 0])
for id in id_numb:
  summa=data[data[:, 0]==id, 4].mean()
  print(f"Mahsulot id : {id} -- O'rtacha qiymat {summa}")



Mahsulot id : 1 -- O'rtacha qiymat 608364.2857142857
Mahsulot id : 2 -- O'rtacha qiymat 562640.5
Mahsulot id : 3 -- O'rtacha qiymat 919359.7777777778
Mahsulot id : 4 -- O'rtacha qiymat 879076.6666666666
Mahsulot id : 5 -- O'rtacha qiymat 595203.0
Mahsulot id : 6 -- O'rtacha qiymat 461764.0
Mahsulot id : 7 -- O'rtacha qiymat 747843.8181818182
Mahsulot id : 8 -- O'rtacha qiymat 707314.6
Mahsulot id : 9 -- O'rtacha qiymat 980634.5
Mahsulot id : 10 -- O'rtacha qiymat 871608.0909090909


22. Har bir do‘kon uchun o‘rtacha tushumni hisoblang.




In [ ]:
store_id=np.unique(data[:, 1])
for id in store_id:
  summa=data[data[:, 0]==id, 4].mean()
  print(f"Store id : {id} -- O'rtacha qiymat {summa}")

Store id : 1 -- O'rtacha qiymat 608364.2857142857
Store id : 2 -- O'rtacha qiymat 562640.5
Store id : 3 -- O'rtacha qiymat 919359.7777777778
Store id : 4 -- O'rtacha qiymat 879076.6666666666
Store id : 5 -- O'rtacha qiymat 595203.0


23. Har bir mahsulotdan nechta dona sotilganini hisoblang.

In [ ]:
id_numb=np.unique(data[:, 0])
for id in id_numb:
  numbers=data[data[:, 0]==id, 2].sum()
  print(f"Mahsulot id: {id}-- Jami: {numbers}")

Mahsulot id: 1-- Jami: 112
Mahsulot id: 2-- Jami: 207
Mahsulot id: 3-- Jami: 226
Mahsulot id: 4-- Jami: 219
Mahsulot id: 5-- Jami: 261
Mahsulot id: 6-- Jami: 151
Mahsulot id: 7-- Jami: 282
Mahsulot id: 8-- Jami: 414
Mahsulot id: 9-- Jami: 361
Mahsulot id: 10-- Jami: 339


24. Revenue bo‘yicha eng katta 5 ta yozuvni chiqaring.

In [ ]:
data1=data[:, 4]
top_5=np.sort(data1)[-5:]
print(f"Eng katta 5 ta qiymatlar: {top_5}")

Eng katta 5 ta qiymatlar: [1955808 1958502 1998914 2197296 2267184]


25. Revenue bo‘yicha eng kichik 5 ta yozuvni chiqaring.




In [ ]:
data1=data[:, 4]
top_5=np.sort(data1)[:5]
print(f"Eng kichik 5 ta qiymatlar: {top_5}")

Eng kichik 5 ta qiymatlar: [29778 41458 44177 50676 53961]


26. Har bir do‘kon bo‘yicha mahsulotlarning o‘rtacha tushumlarini hisoblab, eng samarali do‘konni aniqlang.





In [ ]:
store_id=np.unique(data[:, 1])
store={}
for id in store_id:
  summa=data[data[:, 0]==id, 3].mean()
  print(f"Store id : {id} -- O'rtacha qiymat {summa}")
  store[id]= summa
best_store=max(store, key=store.get)
print(f"Eng samarali do'kon: {best_store}")

Store id : 1 -- O'rtacha qiymat 36684.0
Store id : 2 -- O'rtacha qiymat 27847.6
Store id : 3 -- O'rtacha qiymat 31351.88888888889
Store id : 4 -- O'rtacha qiymat 36544.11111111111
Store id : 5 -- O'rtacha qiymat 24131.4
Eng samarali do'kon: 1


27. Har bir mahsulot bo‘yicha umumiy tushumni hisoblang va eng ko‘p sotilgan TOP-3 mahsulotni chiqaring.




In [ ]:
id_numb=np.unique(data[:, 0])
products={}
for id in id_numb:
  summa=data[data[:, 0]==id, 4].sum()
  print(f"Mahsulot id : {id} -- Jami {summa}")
  products[id]=summa
top_3=sorted(products.items(), key=lambda x:x[1], reverse=True)[:3]
for key, value in top_3:
  print(f"Dokon {key}: {value}")

Mahsulot id : 1 -- Jami 4258550
Mahsulot id : 2 -- Jami 5626405
Mahsulot id : 3 -- Jami 8274238
Mahsulot id : 4 -- Jami 7911690
Mahsulot id : 5 -- Jami 5952030
Mahsulot id : 6 -- Jami 2770584
Mahsulot id : 7 -- Jami 8226282
Mahsulot id : 8 -- Jami 10609719
Mahsulot id : 9 -- Jami 11767614
Mahsulot id : 10 -- Jami 9587689
Dokon 9: 11767614
Dokon 8: 10609719
Dokon 10: 9587689


28. Har bir do‘kon uchun o‘rtacha narx (Unit_Price)ni toping.




In [ ]:
store_id=np.unique(data[:, 1])
for id in store_id:
  sum=data[data[:, 1]==id, 3].mean()
  print(f"Store Id {id}-- o'rtacha narx:-- {sum.round(2)}")

Store Id 1-- o'rtacha narx:-- 26951.21
Store Id 2-- o'rtacha narx:-- 29083.33
Store Id 3-- o'rtacha narx:-- 30459.5
Store Id 4-- o'rtacha narx:-- 30134.55
Store Id 5-- o'rtacha narx:-- 34729.76


29. Revenue ustunini tartiblang (katta → kichik).




In [ ]:
sorted_data= sorted(data[:, 4:], reverse=True)
sorted_data

[array([2267184], dtype=int32),
 array([2197296], dtype=int32),
 array([1998914], dtype=int32),
 array([1958502], dtype=int32),
 array([1955808], dtype=int32),
 array([1849038], dtype=int32),
 array([1721295], dtype=int32),
 array([1654650], dtype=int32),
 array([1643070], dtype=int32),
 array([1494510], dtype=int32),
 array([1432256], dtype=int32),
 array([1385720], dtype=int32),
 array([1340920], dtype=int32),
 array([1339890], dtype=int32),
 array([1300362], dtype=int32),
 array([1285020], dtype=int32),
 array([1279692], dtype=int32),
 array([1248352], dtype=int32),
 array([1230668], dtype=int32),
 array([1201512], dtype=int32),
 array([1197381], dtype=int32),
 array([1090525], dtype=int32),
 array([1068625], dtype=int32),
 array([1062288], dtype=int32),
 array([1046067], dtype=int32),
 array([1034132], dtype=int32),
 array([1029204], dtype=int32),
 array([1008559], dtype=int32),
 array([1006368], dtype=int32),
 array([970515], dtype=int32),
 array([936120], dtype=int32),
 array([91

30. Eng ko‘p tushum qilgan mahsulot va eng ko‘p dona sotilgan mahsulotni taqqoslang (bir xilmi yoki yo‘q?).


In [ ]:
product_ids=np.unique(data[:, 0])
products={}
for id in product_ids:
  sum=data[data[:, 0]==id, 4].sum()
  products[id]=sum
best_product=max(products, key=products.get)
print(f"Eng kop tushum qillgan mahsulot: {best_product}")

Eng kop tushum qillgan mahsulot: 9


In [ ]:
product_ids=np.unique(data[:, 0])
products={}
for id in product_ids:
  sum=data[data[:, 0]==id, 3].sum()
  products[id]=sum
best_product=max(products, key=products.get)
print(f"Eng kop dona sotilgan mahsulot : {best_product}")
print(f"Eng kop tushum qillgan mahsulot: {best_product}")
print("Demak bir xil emas ")

Eng kop dona sotilgan mahsulot : 8
Eng kop tushum qillgan mahsulot: 8
Demak bir xil emas 
