<a href="https://colab.research.google.com/github/Bilol2747/python_darslarim/blob/main/Sorted_%2C_Takrorlanmas_(m).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
arr=np.random.rand(4)
arr

array([0.85590142, 0.15499599, 0.15362445, 0.07427661])

In [5]:
np.sort(arr)

array([0.07427661, 0.15362445, 0.15499599, 0.85590142])

In [6]:
sorted_arr=np.sort(arr)
sorted_arr

array([0.07427661, 0.15362445, 0.15499599, 0.85590142])

In [7]:
rev_arr=-np.sort(-arr)
rev_arr

array([0.85590142, 0.15499599, 0.15362445, 0.07427661])

In [8]:
arr1=np.random.randn(2, 4)
arr1

array([[ 0.76339667, -0.93719206, -0.1623134 , -2.1088075 ],
       [ 0.73766211, -0.41751187,  0.53145722,  0.27301107]])

In [11]:
row_sorted=-np.sort(-arr1, axis=1)
row_sorted

array([[ 0.76339667, -0.1623134 , -0.93719206, -2.1088075 ],
       [ 0.73766211,  0.53145722,  0.27301107, -0.41751187]])

# Uniqe, in1d, setdiff1d va boshqa usullar haqida

In [23]:
names=np.array(['Sarvar', 'Abdurahmon', ' Saloh', 'Temur', 'Sarvar', " Ilhom"])
ints=np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [13]:
np.unique(names)

array(['Abdurahmon', 'Hasan', 'Sarvar', 'Temur'], dtype='<U10')

In [14]:
names

array(['Sarvar', 'Abdurahmon', 'Hasan', 'Temur', 'Sarvar', 'Temur'],
      dtype='<U10')

In [16]:
set(names)

{'Abdurahmon', 'Hasan', 'Sarvar', 'Temur'}

In [17]:
np.unique(ints)

array([1, 2, 3, 4])

In [18]:
arr1=np.array([6, 0, 0, 3, 2, 5, 6])
arr2=np.array([0, 2, 3])

In [19]:
np.in1d(arr1, arr2)

array([False,  True,  True,  True,  True, False, False])

In [20]:
names

array(['Sarvar', 'Abdurahmon', 'Hasan', 'Temur', 'Sarvar', 'Temur'],
      dtype='<U10')

In [21]:
names1=np.array(['Sarvar',  'Bilol', 'Hasan', ' Jalol', 'Sarvar', 'Temur'])

In [24]:
np.setdiff1d(names, names1)

array([' Ilhom', ' Saloh', 'Abdurahmon'], dtype='<U10')