<a href="https://colab.research.google.com/github/Bilol2747/python_darslarim/blob/main/Universal_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



> Add blockquote
#Unary functions


In [1]:
import numpy as np

In [3]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [9]:
np.log(arr)

<ipython-input-9-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [10]:
arr1=np.random.randn(6)
arr1

array([-1.1170957 , -1.145098  , -1.06918529,  2.35947969, -2.37461594,
       -0.72096552])

In [14]:
 butun, qoldiq=np.modf(arr1)


In [17]:
print(butun)


[-0.1170957  -0.145098   -0.06918529  0.35947969 -0.37461594 -0.72096552]


In [20]:
np.sign(arr1)


array([-1., -1., -1.,  1., -1., -1.])

In [21]:
arr1

array([-1.1170957 , -1.145098  , -1.06918529,  2.35947969, -2.37461594,
       -0.72096552])

In [22]:
arr1

array([-1.1170957 , -1.145098  , -1.06918529,  2.35947969, -2.37461594,
       -0.72096552])

In [23]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [24]:
arr1[1]=np.NaN

In [25]:
arr1

array([-1.1170957 ,         nan, -1.06918529,  2.35947969, -2.37461594,
       -0.72096552])

In [26]:
np.isnan(arr1)

array([False,  True, False, False, False, False])

# New Section

#Binary functions

In [27]:
arr2=np.random.randn(6)
arr3=np.random.randn(6)

In [28]:
arr2

array([-2.32879554,  0.69041654,  1.15880539,  1.15255359,  0.76532889,
       -0.21226889])

In [29]:
arr3

array([0.79369005, 1.77564709, 0.83172729, 0.56174256, 0.0141633 ,
       1.14535217])

In [30]:
np.add(arr2, arr3)

array([-1.53510549,  2.46606364,  1.99053269,  1.71429615,  0.77949219,
        0.93308329])

In [31]:
np.multiply(arr2, arr3)

array([-1.84834186,  1.22593613,  0.96381007,  0.64743841,  0.01083958,
       -0.24312263])

In [32]:
arr2*arr3

array([-1.84834186,  1.22593613,  0.96381007,  0.64743841,  0.01083958,
       -0.24312263])

In [33]:
np.maximum(arr2, arr3)

array([0.79369005, 1.77564709, 1.15880539, 1.15255359, 0.76532889,
       1.14535217])

In [34]:
arr2

array([-2.32879554,  0.69041654,  1.15880539,  1.15255359,  0.76532889,
       -0.21226889])

In [35]:
arr3

array([0.79369005, 1.77564709, 0.83172729, 0.56174256, 0.0141633 ,
       1.14535217])