<a href="https://colab.research.google.com/github/Bilol2747/python_darslarim/blob/main/Where_(massive).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Massivega yo'naltirilgan dasturlash

In [1]:
import numpy as np

In [2]:
xarr=np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr=np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [3]:
son=np.array([True, False, True, True, False])


In [4]:
result=np.where(son, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [5]:
arr=np.random.randn(4, 4)
arr

array([[-0.85089788, -0.15090735, -0.55398223,  1.53229601],
       [-2.15269517, -0.73818351, -0.47237043, -0.03396435],
       [-1.03882882, -1.55111783,  0.23059822, -1.40118121],
       [-1.06823068,  0.0108004 , -0.59397532, -0.90605812]])

In [6]:
results=np.where(arr<0, -2, 2)
results

array([[-2, -2, -2,  2],
       [-2, -2, -2, -2],
       [-2, -2,  2, -2],
       [-2,  2, -2, -2]])

In [10]:
re=np.where(arr>0,  1,  -1)
re

array([[-1, -1, -1,  1],
       [-1, -1, -1, -1],
       [-1, -1,  1, -1],
       [-1,  1, -1, -1]])

#Arifmetik Amallar

In [16]:
arr1=np.arange(6).reshape(2, 3)
arr2=np.arange(6, 12).reshape(2, 3)
arr1
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
arr1+arr2

array([[ 6,  8, 10],
       [12, 14, 16]])

In [19]:
arr1*arr2

array([[ 0,  7, 16],
       [27, 40, 55]])

In [21]:
arr2/arr1

<ipython-input-21-e2e60495effe>:1: RuntimeWarning: divide by zero encountered in divide
  arr2/arr1


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [22]:
arr2-arr1

array([[6, 6, 6],
       [6, 6, 6]])

In [23]:
arr1
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
arr1**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [26]:
arr2**3

array([[ 216,  343,  512],
       [ 729, 1000, 1331]])

In [28]:
arr2**(1/2)

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

In [29]:
arr2**0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

# Matematik va statistik usullarni qo'llash

In [30]:
arr=np.random.randn(5, 4)

In [31]:
arr

array([[ 0.7687714 ,  0.78446476,  0.30026448, -0.29776392],
       [-0.1355508 ,  1.67910659, -0.47875927,  0.06885602],
       [-0.94287953,  0.25421776,  1.09779846, -0.60560637],
       [ 1.28414996,  0.88649934, -0.5961494 ,  0.2050192 ],
       [-1.18950906,  0.23829609, -1.15070672,  0.06446409]])

In [33]:
arr.sum()

2.234983097877648

In [34]:
arr[0]

array([ 0.7687714 ,  0.78446476,  0.30026448, -0.29776392])

In [36]:
np.sum(arr, axis=1)

array([ 1.55573673,  1.13365255, -0.19646967,  1.7795191 , -2.03745561])

In [38]:
arr.sum(axis=0)

array([-0.21501803,  3.84258456, -0.82755245, -0.56503097])

In [39]:
data=np.arange(0, 5)

In [40]:
data

array([0, 1, 2, 3, 4])

In [41]:
data.mean()

2.0

In [42]:
np.mean(data)

2.0

In [43]:
arr.mean()

0.1117491548938824

In [44]:
np.mean(arr)

0.1117491548938824

In [45]:

np.mean(arr, axis=1)

array([ 0.38893418,  0.28341314, -0.04911742,  0.44487977, -0.5093639 ])

In [46]:
arr

array([[ 0.7687714 ,  0.78446476,  0.30026448, -0.29776392],
       [-0.1355508 ,  1.67910659, -0.47875927,  0.06885602],
       [-0.94287953,  0.25421776,  1.09779846, -0.60560637],
       [ 1.28414996,  0.88649934, -0.5961494 ,  0.2050192 ],
       [-1.18950906,  0.23829609, -1.15070672,  0.06446409]])

In [47]:
arr.mean(axis=0)

array([-0.04300361,  0.76851691, -0.16551049, -0.11300619])

In [48]:
#cumsum

In [49]:
data

array([0, 1, 2, 3, 4])

In [51]:
data.cumsum()

array([ 0,  1,  3,  6, 10])

In [53]:
data.sum()

10

In [54]:
arr

array([[ 0.7687714 ,  0.78446476,  0.30026448, -0.29776392],
       [-0.1355508 ,  1.67910659, -0.47875927,  0.06885602],
       [-0.94287953,  0.25421776,  1.09779846, -0.60560637],
       [ 1.28414996,  0.88649934, -0.5961494 ,  0.2050192 ],
       [-1.18950906,  0.23829609, -1.15070672,  0.06446409]])

In [56]:
arr.cumsum()

array([0.7687714 , 1.55323616, 1.85350064, 1.55573673, 1.42018593,
       3.09929253, 2.62053326, 2.68938928, 1.74650975, 2.00072751,
       3.09852597, 2.49291961, 3.77706956, 4.6635689 , 4.0674195 ,
       4.27243871, 3.08292964, 3.32122573, 2.17051901, 2.2349831 ])

# Tartiblash(Sorting)